import { createSlice } from "@reduxjs/toolkit";

const initialState = [
  {
    name: "Evelyn",
    assignment: "SCRUM",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D1-1",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W1D2-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W1D2-2",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D2-3",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W1D2-4",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D2-5",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D3-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D3-2",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D3-4",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D3-5",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D3",
    difficult: "5",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W1D4-1",
    difficult: "4",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W1D4",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W1D5",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W2D1-1",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W2D1-2",
    difficult: "2",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W2D2-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D2-2",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D2-3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D3-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D3-2",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W2D3-3",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D4-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W2D4-2",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W2D4-3",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W2D5",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D1-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D1-2",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D1-3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D1-4",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W3D2-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D2-2",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W3D2-3",
    difficult: "3",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D3-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W3D3-2",
    difficult: "4",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D3-3",
    difficult: "3",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D3-4",
    difficult: "4",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D4-1",
    difficult: "5",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D4-2",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W3D5",
    difficult: "2",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D2-1",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D2-2",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D2-3",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D2-4",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3-1",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3-2",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3-3",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3-4",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3-5",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W4D3",
    difficult: "1",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W5D4-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Evelyn",
    assignment: "W5D5",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W6D1-1",
    difficult: "5",
    fun: "5",
  },
  {
    name: "Evelyn",
    assignment: "W6D2-1",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Evelyn",
    assignment: "W6D2",
    difficult: "5",
    fun: "5",
  },
  {
    name: "Aranka",
    assignment: "SCRUM",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W1D1-1",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W1D2-1",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W1D2-2",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W1D2-3",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W1D2-4",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W1D2-5",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W1D3-1",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W1D3-2",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W1D3-4",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W1D3-5",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W1D3",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W1D4-1",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W1D4",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W1D5",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W2D1-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D1-2",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D2-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D2-2",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D2-3",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D3-1",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W2D3-2",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W2D3-3",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W2D4-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Aranka",
    assignment: "W2D4-2",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W2D4-3",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W2D5",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W3D1-1",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W3D1-2",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W3D1-3",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Aranka",
    assignment: "W3D1-4",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D2-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D2-2",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D2-3",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D3-1",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W3D3-2",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D3-3",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D3-4",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W3D4-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W3D4-2",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W3D5",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W4D2-1",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W4D2-2",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W4D2-3",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W4D2-4",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Aranka",
    assignment: "W4D3-1",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W4D3-2",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Aranka",
    assignment: "W4D3-3",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W4D3-4",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W4D3-5",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W4D3",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Aranka",
    assignment: "W5D4-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Aranka",
    assignment: "W5D5",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W6D1-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Aranka",
    assignment: "W6D2-1",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Aranka",
    assignment: "W6D2",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "SCRUM",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W1D1-1",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W1D2-1",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W1D2-2",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W1D2-3",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W1D2-4",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W1D2-5",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W1D3-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W1D3-2",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W1D3-4",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W1D3-5",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W1D3",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W1D4-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W1D4",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W1D5",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W2D1-1",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W2D1-2",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W2D2-1",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W2D2-2",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W2D2-3",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W2D3-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W2D3-2",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W2D3-3",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W2D4-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W2D4-2",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W2D4-3",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W2D5",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W3D1-1",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W3D1-2",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W3D1-3",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W3D1-4",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W3D2-1",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W3D2-2",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W3D2-3",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W3D3-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W3D3-2",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W3D3-3",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W3D3-4",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W3D4-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W3D4-2",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W3D5",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W4D2-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W4D2-2",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W4D2-3",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W4D2-4",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W4D3-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W4D3-2",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Floris",
    assignment: "W4D3-3",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W4D3-4",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W4D3-5",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W4D3",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W5D4-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Floris",
    assignment: "W5D5",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W6D1-1",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Floris",
    assignment: "W6D2-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Floris",
    assignment: "W6D2",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "SCRUM",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W1D1-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W1D2-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W1D2-2",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W1D2-3",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W1D2-4",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W1D2-5",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W1D3-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W1D3-2",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W1D3-4",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W1D3-5",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W1D3",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W1D4-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W1D4",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W1D5",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W2D1-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W2D1-2",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W2D2-1",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W2D2-2",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W2D2-3",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W2D3-1",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W2D3-2",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W2D3-3",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W2D4-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W2D4-2",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W2D4-3",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W2D5",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W3D1-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W3D1-2",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W3D1-3",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W3D1-4",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W3D2-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W3D2-2",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W3D2-3",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W3D3-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W3D3-2",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W3D3-3",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W3D3-4",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W3D4-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W3D4-2",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W3D5",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W4D2-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W4D2-2",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W4D2-3",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W4D2-4",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W4D3-1",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W4D3-2",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W4D3-3",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W4D3-4",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Hector",
    assignment: "W4D3-5",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W4D3",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W5D4-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Hector",
    assignment: "W5D5",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W6D1-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Hector",
    assignment: "W6D2-1",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Hector",
    assignment: "W6D2",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "SCRUM",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W1D1-1",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W1D2-1",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Martina",
    assignment: "W1D2-2",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W1D2-3",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W1D2-4",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Martina",
    assignment: "W1D2-5",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W1D3-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W1D3-2",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W1D3-4",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Martina",
    assignment: "W1D3-5",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W1D3",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Martina",
    assignment: "W1D4-1",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Martina",
    assignment: "W1D4",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Martina",
    assignment: "W1D5",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W2D1-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W2D1-2",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Martina",
    assignment: "W2D2-1",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W2D2-2",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Martina",
    assignment: "W2D2-3",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W2D3-1",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Martina",
    assignment: "W2D3-2",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W2D3-3",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Martina",
    assignment: "W2D4-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W2D4-2",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W2D4-3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W2D5",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W3D1-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W3D1-2",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Martina",
    assignment: "W3D1-3",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W3D1-4",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Martina",
    assignment: "W3D2-1",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Martina",
    assignment: "W3D2-2",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W3D2-3",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W3D3-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W3D3-2",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W3D3-3",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Martina",
    assignment: "W3D3-4",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Martina",
    assignment: "W3D4-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W3D4-2",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W3D5",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Martina",
    assignment: "W4D2-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W4D2-2",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Martina",
    assignment: "W4D2-3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W4D2-4",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W4D3-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W4D3-2",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Martina",
    assignment: "W4D3-3",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W4D3-4",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W4D3-5",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Martina",
    assignment: "W4D3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W5D4-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W5D5",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W6D1-1",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Martina",
    assignment: "W6D2-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Martina",
    assignment: "W6D2",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "SCRUM",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W1D1-1",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W1D2-1",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W1D2-2",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W1D2-3",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W1D2-4",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W1D2-5",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W1D3-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W1D3-2",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W1D3-4",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W1D3-5",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W1D3",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W1D4-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W1D4",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W1D5",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W2D1-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W2D1-2",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W2D2-1",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W2D2-2",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W2D2-3",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W2D3-1",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W2D3-2",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W2D3-3",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W2D4-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W2D4-2",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W2D4-3",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W2D5",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W3D1-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W3D1-2",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W3D1-3",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W3D1-4",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W3D2-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W3D2-2",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W3D2-3",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W3D3-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W3D3-2",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W3D3-3",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W3D3-4",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W3D4-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W3D4-2",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W3D5",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W4D2-1",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W4D2-2",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W4D2-3",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W4D2-4",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W4D3-1",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W4D3-2",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W4D3-3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W4D3-4",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W4D3-5",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Maurits",
    assignment: "W4D3",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W5D4-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W5D5",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Maurits",
    assignment: "W6D1-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Maurits",
    assignment: "W6D2-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Maurits",
    assignment: "W6D2",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "SCRUM",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W1D1-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W1D2-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W1D2-2",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W1D2-3",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W1D2-4",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W1D2-5",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W1D3-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W1D3-2",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W1D3-4",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W1D3-5",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W1D3",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W1D4-1",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W1D4",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W1D5",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W2D1-1",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W2D1-2",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W2D2-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W2D2-2",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W2D2-3",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W2D3-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W2D3-2",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W2D3-3",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W2D4-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W2D4-2",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W2D4-3",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W2D5",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W3D1-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W3D1-2",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W3D1-3",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W3D1-4",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W3D2-1",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W3D2-2",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W3D2-3",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W3D3-1",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W3D3-2",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W3D3-3",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W3D3-4",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W3D4-1",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W3D4-2",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W3D5",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W4D2-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W4D2-2",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W4D2-3",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W4D2-4",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W4D3-1",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W4D3-2",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W4D3-3",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Rahima",
    assignment: "W4D3-4",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W4D3-5",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W4D3",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Rahima",
    assignment: "W5D4-1",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W5D5",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Rahima",
    assignment: "W6D1-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W6D2-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Rahima",
    assignment: "W6D2",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Sandra",
    assignment: "SCRUM",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Sandra",
    assignment: "W1D1-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W1D2-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W1D2-2",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W1D2-3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W1D2-4",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Sandra",
    assignment: "W1D2-5",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W1D3-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Sandra",
    assignment: "W1D3-2",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Sandra",
    assignment: "W1D3-4",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W1D3-5",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W1D3",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W1D4-1",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W1D4",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W1D5",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W2D1-1",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Sandra",
    assignment: "W2D1-2",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W2D2-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W2D2-2",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W2D2-3",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W2D3-1",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W2D3-2",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W2D3-3",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W2D4-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W2D4-2",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W2D4-3",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W2D5",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W3D1-1",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W3D1-2",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W3D1-3",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W3D1-4",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W3D2-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W3D2-2",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W3D2-3",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W3D3-1",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W3D3-2",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W3D3-3",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W3D3-4",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W3D4-1",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W3D4-2",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Sandra",
    assignment: "W3D5",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W4D2-1",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W4D2-2",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Sandra",
    assignment: "W4D2-3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W4D2-4",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W4D3-1",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Sandra",
    assignment: "W4D3-2",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W4D3-3",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W4D3-4",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W4D3-5",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W4D3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W5D4-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Sandra",
    assignment: "W5D5",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Sandra",
    assignment: "W6D1-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Sandra",
    assignment: "W6D2-1",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Sandra",
    assignment: "W6D2",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "SCRUM",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W1D1-1",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W1D2-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D2-2",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W1D2-3",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W1D2-4",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W1D2-5",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D3-1",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W1D3-2",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D3-4",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W1D3-5",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D3",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D4-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W1D4",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W1D5",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W2D1-1",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W2D1-2",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W2D2-1",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W2D2-2",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W2D2-3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W2D3-1",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W2D3-2",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W2D3-3",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W2D4-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W2D4-2",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W2D4-3",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W2D5",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W3D1-1",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W3D1-2",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D1-3",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W3D1-4",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D2-1",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W3D2-2",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W3D2-3",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D3-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D3-2",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W3D3-3",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W3D3-4",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D4-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W3D4-2",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W3D5",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W4D2-1",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W4D2-2",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W4D2-3",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W4D2-4",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W4D3-1",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W4D3-2",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W4D3-3",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W4D3-4",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Wietske",
    assignment: "W4D3-5",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Wietske",
    assignment: "W4D3",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W5D4-1",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W5D5",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Wietske",
    assignment: "W6D1-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W6D2-1",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Wietske",
    assignment: "W6D2",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "SCRUM",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W1D1-1",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W1D2-1",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W1D2-2",
    difficult: "1",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W1D2-3",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W1D2-4",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W1D2-5",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W1D3-1",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W1D3-2",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W1D3-4",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W1D3-5",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W1D3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W1D4-1",
    difficult: "4",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W1D4",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W1D5",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W2D1-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W2D1-2",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W2D2-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W2D2-2",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W2D2-3",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W2D3-1",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W2D3-2",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W2D3-3",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W2D4-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W2D4-2",
    difficult: "4",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W2D4-3",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W2D5",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W3D1-1",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W3D1-2",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W3D1-3",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W3D1-4",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W3D2-1",
    difficult: "1",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W3D2-2",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W3D2-3",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W3D3-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W3D3-2",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W3D3-3",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W3D3-4",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W3D4-1",
    difficult: "2",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W3D4-2",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W3D5",
    difficult: "3",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W4D2-1",
    difficult: "2",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W4D2-2",
    difficult: "3",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W4D2-3",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W4D2-4",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W4D3-1",
    difficult: "3",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W4D3-2",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W4D3-3",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W4D3-4",
    difficult: "3",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W4D3-5",
    difficult: "2",
    fun: "3",
  },
  {
    name: "Storm",
    assignment: "W4D3",
    difficult: "4",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W5D4-1",
    difficult: "2",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W5D5",
    difficult: "1",
    fun: "2",
  },
  {
    name: "Storm",
    assignment: "W6D1-1",
    difficult: "4",
    fun: "4",
  },
  {
    name: "Storm",
    assignment: "W6D2-1",
    difficult: "1",
    fun: "1",
  },
  {
    name: "Storm",
    assignment: "W6D2",
    difficult: "3",
    fun: "3",
  },
];

const studentSlice = createSlice({
  name: "student",
  initialState,
  reducers: {
    studentTest(state, action) {
      state = action.payload;
    },
  },
});

export const { studentDelete, studentTest } = studentSlice.actions;

export default studentSlice.reducer;
